#!/bin/bash

dev="$1"
action="$2"
echo $1 - $2 >>/tmp/log
case "$dev" in 
eth0)
    case "$action" in
    in) 
	systemctl stop wac
	systemctl stop hotspot
	systemctl stop wireless
	#sleep 1
	ifconfig wlan0 down
	ip addr flush wlan0
	ifconfig wlan0 up
	cat /sys/class/net/eth0/address >/tmp/mac
        systemctl restart airplay
	#killall dhcpcd
	systemctl start dhcpcd
	echo lan >/tmp/networkstatus
	
        ;;
    out)
	ip addr flush dev eth0
	systemctl restart wireless
        ;;
     probe)
	#systemctl stop wac
	systemctl stop hotspot
	#sleep 1
     	ifconfig eth0 up
	cable="$(grep "" /sys/class/net/eth0/carrier)"
	if [ $cable == "0" ]; then
		systemctl restart wireless &
	fi
	
	exit 0
   esac
   ;;
wlan0)
	case "$action" in
    in)
        cat /sys/class/net/wlan0/address >/tmp/mac
        ;;
    out)
	#systemctl stop wac
	systemctl stop hotspot
	cable="$(grep "" /sys/class/net/eth0/carrier)"
 	if [ $cable == "0" ]; then
 		if ! (systemctl -q is-active wireless.service)
		then
			systemctl start wireless
		fi
	fi
	;;
    probe)
	;;
    esac
    ;;
esac

